#server
server:
  port: 10000


#jdbc
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/english
    username: root
    password: qweasd123!

  #jpa
  jpa:
    hibernate:
      #jpa ddl-auto
      #create: DROP 후 CREATE
      #create-drop: DROP 후 CREATE 후 DROP, DML을 사용하지 않는 다면 DROP되지 않음
      #update: Entity와 DB 스키마 비교 후 수정 사항 반영(컬럼 추가)
      #validate: Entity와 DB 스키마 비교(다르면 예외 발생)
      ddl-auto: create

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always